services:
  - type: pserv
    name: mariadb
    runtime: image
    plan: starter
    region: virginia
    image:
      url: ghcr.io/wersplat/mariadb:10.6
    envVars:
      - key: MARIADB_ROOT_PASSWORD
        sync: false
      - key: MARIADB_DATABASE
        sync: false
      - key: MARIADB_USER
        sync: false
      - key: MARIADB_PASSWORD
        sync: false
    disk:
      name: data
      sizeGB: 10
      mountPath: /var/lib/mysql

  - type: web
    name: wordpress
    runtime: image
    plan: starter
    region: virginia
    image:
      url: ghcr.io/wersplat/wordpress-nginx:latest
    envVars:
      - key: WORDPRESS_DATABASE_HOST
        value: mariadb
      - key: WORDPRESS_DATABASE_USER
        sync: false
      - key: WORDPRESS_DATABASE_NAME
        sync: false
      - key: WORDPRESS_DATABASE_PASSWORD
        sync: false
