services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - mariadb_data:/bitnami/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}

  wordpress:
    image: docker.io/bitnami/wordpress-nginx:latest     # ← switch to the NGINX bundle
    ports:
      - "80:8080"                                        # maps host 80 → container 8080
      - "443:8443"                                       # if you later add SSL
    volumes:
      - wordpress_data:/bitnami/wordpress
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=${MARIADB_USER}
      - WORDPRESS_DATABASE_NAME=${MARIADB_DATABASE}
      - WORDPRESS_DATABASE_PASSWORD=${MARIADB_PASSWORD}
volumes:
  mariadb_data:
  wordpress_data: