name: Docs Sync

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'obsidian/**'

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync Obsidian vault to docs
        run: bash scripts/obsidian-export.sh
