name: Welcome New Contributors

on:
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Greet first-time contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '👋 Welcome! Thanks for opening your first issue. Please review our CONTRIBUTING.md.'
          pr-message: '🎉 Thanks for your first pull request! Please be sure to follow our [contribution guidelines](../blob/main/CONTRIBUTING.md).'
